name: Demo Environment Secret

on:
  workflow_dispatch:    # allows manual run from Actions tab

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    # Bind this job to the "production" environment
    environment:
      name: production
      url: https://github.com/myorgkevin94/first_repo/settings/environments/10579021663   # just a demo URL for display

    steps:
      - name: Print environment name
        run: echo "Environment is:${{job.environment}}"

      - name: Use PROD_API_KEY
        run: echo "Prod API key is:${{secrets.PROD_API_KEY}}"
