name: Demo Environment Secret

on:
  workflow_dispatch:

env:
  DEPLOY_ENV: prod   # allowed in expressions

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    environment:
      name: ${{env.DEPLOY_ENV}}
      url: https://example.com

    env:
      DEPLOY_ENV: ${{env.DEPLOY_ENV}}   # make it available to steps

    steps:
      - name: Print environment name
        run: echo "Environment is:$DEPLOY_ENV"

      - name: Use PROD_API_KEY
        run: echo "Prod API key is:${{secrets.PROD_API_KEY}}"
