name: Demo Environment Secret

on:
  workflow_dispatch:    # allows manual run from Actions tab
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'prod'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    # Bind this job to the "production" environment
    environment:
      name: ${{ inputs.environment }}   # THIS works
      url: https://example.com

    steps:
      - name: Print environment name
        run: echo "Environment is:${{inputs.environment}}"

      - name: Use PROD_API_KEY
        run: echo "Prod API key is:${{secrets.PROD_API_KEY}}"
